import { chromium } from '@playwright/test';
import { readFileSync } from 'node:fs';
const folder = process.argv[2] || 'evidencias/jenkins';
const password = readFileSync('.runtime/controller.env','utf8').match(/^ADMIN_PASSWORD=(.+)$/m)[1];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto('http://127.0.0.1:8080/login');
await page.locator('input[name="j_username"]').fill('admin');
await page.locator('input[name="j_password"]').fill(password);
await page.getByRole('button', { name: /sign in|log in|entrar/i }).click();
await page.waitForURL(url => !url.pathname.includes('/login'));
await page.goto('http://127.0.0.1:8080/computer/');
await page.screenshot({ path: `${folder}/controller-agents.png`, fullPage: true });
await page.goto(`http://127.0.0.1:8080/job/carparts/job/${encodeURIComponent(process.env.LAB_BRANCH || 'main')}/`);
await page.getByText('Qualidade', { exact: false }).first().waitFor({ timeout: 30000 });
await page.screenshot({ path: `${folder}/stage-view.png`, fullPage: true });
await page.goto('http://127.0.0.1:8080/job/carparts/');
await page.screenshot({ path: `${folder}/multibranch.png`, fullPage: true });
await browser.close();
